export let jackets = [
  {
    id: "100001",
    name: "Jacket 1",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Varius tincidunt non cursus id fusce.",
    price: "699.00",
    image: "/images/jacket1yellow.jpg",
    popular: "true",
    onsale: "true",
  },
  {
    id: "100002",
    name: "Jacket 2",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Varius tincidunt non cursus id fusce.",
    price: "599.00",
    image: "/images/jacket2red.jpg",
  },
  {
    id: "100003",
    name: "Jacket 3",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Varius tincidunt non cursus id fusce.",
    price: "799.00",
    image: "/images/jacket3green.jpg",
    popular: "true",
  },
  {
    id: "100004",
    name: "Jacket 4",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Varius tincidunt non cursus id fusce.",
    price: "899.00",
    image: "/images/jacket4black.jpg",
  },
  {
    id: "100005",
    name: "Jacket 5",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Varius tincidunt non cursus id fusce.",
    price: "1199.00",
    image: "/images/jacket5.jpg",
    popular: "true",
  },
  {
    id: "100006",
    name: "Jacket 6",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Varius tincidunt non cursus id fusce.",
    price: "749.00",
    image: "/images/jacket6.jpg",
  },
  {
    id: "100007",
    name: "Jacket 7",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Varius tincidunt non cursus id fusce.",
    price: "899.00",
    image: "/images/jacket7.jpg",
  },
  {
    id: "100008",
    name: "Jacket 8",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Varius tincidunt non cursus id fusce.",
    price: "499.00",
    image: "/images/jacket8.jpg",
  },
];
